apiVersion: v1
kind: Namespace
metadata:
  name: codexa-ai

---

apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: codexa-ai
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: codexa-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "120Mi"
              cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: codexa-ai
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
